# Generated by Django 4.2 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="telegram_chat_id"
            ),
        ),
    ]
