# Generated by Django 4.2 on 2024-09-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_deactivated",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="deactivated"
            ),
        ),
    ]
